name: Deploy to IONOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    - name: Export static files
      run: |
        if [ -f "next.config.js" ]; then
          echo "const nextConfig = { output: 'export', trailingSlash: true, images: { unoptimized: true } }; module.exports = nextConfig;" > next.config.js
        fi
        npm run build

    # Option 1: IONOS Deploy Now (Recommended)
    - name: Deploy to IONOS Deploy Now
      if: github.ref == 'refs/heads/main'
      uses: ionos-cloud/github-action-deploy-now@v2
      with:
        api-key: ${{ secrets.IONOS_API_KEY }}
        service-host: ${{ secrets.IONOS_SERVICE_HOST }}
        
    # Option 2: FTP Deployment (Alternative)
    # Uncomment if using FTP instead of Deploy Now
    # - name: Deploy via FTP
    #   if: github.ref == 'refs/heads/main'
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./out/
    #     server-dir: /